/**
 * Madhukar Munde — Portfolio Paintings Data
 * Images sourced from the Exhibition folder on Google Drive
 */
const PAINTINGS = [
    { id: 1, title: "Untitled 1", dimensions: '54" x 21"', medium: "Acrylic & Oil on Canvas", category: "landscapes", image: "images/paintings/painting-01.jpg" },
    { id: 2, title: "Untitled 2", dimensions: '56" x 21"', medium: "Acrylic & Oil on Canvas", category: "deity", image: "images/paintings/painting-02.jpg" },
    { id: 3, title: "Untitled 3", dimensions: '60" x 42"', medium: "Acrylic & Oil on Canvas", category: "deity", image: "images/paintings/painting-03.jpg" },
    { id: 4, title: "Untitled 4", dimensions: '60" x 48"', medium: "Acrylic & Oil on Canvas", category: "deity", image: "images/paintings/painting-04.jpg" },
    { id: 5, title: "Untitled 5", dimensions: '59" x 44"', medium: "Acrylic & Oil on Canvas", category: "deity", image: "images/paintings/painting-05.jpg" },
    { id: 6, title: "Untitled 6", dimensions: '59" x 44"', medium: "Acrylic & Oil on Canvas", category: "deity", image: "images/paintings/painting-06.jpg" },
    { id: 7, title: "Untitled 7", dimensions: '42" x 36"', medium: "Acrylic on Canvas", category: "landscapes", image: "images/paintings/painting-07.jpg" },
    { id: 8, title: "Untitled 8", dimensions: '42" x 36"', medium: "Acrylic on Canvas", category: "creatures", image: "images/paintings/painting-08.jpg" },
    { id: 9, title: "Untitled 9", dimensions: '42" x 36"', medium: "Acrylic on Canvas", category: "creatures", image: "images/paintings/painting-09.jpg" },
    { id: 10, title: "Untitled 10", dimensions: '42" x 36"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-10.jpg" },
    { id: 11, title: "Untitled 11", dimensions: '59" x 44"', medium: "Acrylic on Canvas", category: "landscapes", image: "images/paintings/painting-11.jpg" },
    { id: 12, title: "Untitled 12", dimensions: '59" x 44"', medium: "Acrylic on Canvas", category: "landscapes", image: "images/paintings/painting-12.jpg" },
    { id: 13, title: "Untitled 13", dimensions: '60" x 50"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-13.jpg" },
    { id: 14, title: "Untitled 14", dimensions: '24" x 20"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-14.jpg" },
    { id: 15, title: "Untitled 15", dimensions: '24" x 20"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-15.jpg" },
    { id: 16, title: "Untitled 16", dimensions: '24" x 20"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-16.jpg" },
    { id: 17, title: "Untitled 17", dimensions: '42" x 36"', medium: "Acrylic on Canvas", category: "creatures", image: "images/paintings/painting-17.jpg" },
    { id: 18, title: "Untitled 18", dimensions: '30" x 22"', medium: "Acrylic on Canvas Board", category: "deity", image: "images/paintings/painting-18.jpg" },
    { id: 19, title: "Untitled 19", dimensions: '30" x 22"', medium: "Acrylic on Canvas Board", category: "deity", image: "images/paintings/painting-19.jpg" },
    { id: 20, title: "Untitled 20", dimensions: '30" x 22"', medium: "Acrylic on Canvas Board", category: "deity", image: "images/paintings/painting-20.jpg" },
    { id: 21, title: "Untitled 21", dimensions: '24" x 18"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-21.jpg" },
    { id: 22, title: "Untitled 22", dimensions: '30" x 36"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-22.jpg" },
    { id: 23, title: "Untitled 23", dimensions: '30" x 18"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-23.jpg" },
    { id: 24, title: "Untitled 24", dimensions: '30" x 18"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-24.jpg" },
    { id: 25, title: "Untitled 25", dimensions: '30" x 20"', medium: "Acrylic on Canvas Board", category: "deity", image: "images/paintings/painting-25.jpg" },
    { id: 26, title: "Untitled 26", dimensions: '50" x 30"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-26.jpg" },
    { id: 27, title: "Untitled 27", dimensions: '59" x 44"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-27.jpg" },
    { id: 28, title: "Untitled 28", dimensions: '50" x 30"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-28.jpg" },
    { id: 29, title: "Untitled 29", dimensions: '50" x 30"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-29.jpg" },
    { id: 30, title: "Untitled 30", dimensions: '60" x 48"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-30.jpg" },
    { id: 31, title: "Untitled 31", dimensions: '50" x 30"', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-31.jpg" },
    { id: 32, title: "Untitled 32", dimensions: '50" x 30"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-32.jpg" },
    { id: 33, title: "Deity Composition", dimensions: '', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-33.jpg" },
    { id: 34, title: "Geometric Deer", dimensions: '', medium: "Acrylic on Canvas", category: "creatures", image: "images/paintings/painting-34.jpg" },
    { id: 35, title: "Sacred Face", dimensions: '', medium: "Acrylic on Canvas", category: "deity", image: "images/paintings/painting-35.jpg" },
    { id: 36, title: "Red Sky", dimensions: '60" x 36"', medium: "Acrylic on Canvas", category: "landscapes", image: "images/paintings/painting-36.jpg" },
    { id: 37, title: "Life", dimensions: '60" x 48"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-37.jpg" },
    { id: 38, title: "Three Stages of Life", dimensions: '44" x 59"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-38.jpg" },
    { id: 39, title: "Kalpvruksha", dimensions: '60" x 50"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-39.jpg" },
    { id: 40, title: "Three Stages", dimensions: '59" x 44"', medium: "Acrylic on Canvas", category: "trees", image: "images/paintings/painting-40.jpg" },
];
